export default {
  "installation": "Installation",
  "scanner": "Barcode-Scanner",
  "batch-scan": "Batch-Scan-Modus",
  "schnellzugriff": "Schnellzugriff-Karten",
  "offline": "Offline-Modus",
  "push-notifications": "Push-Benachrichtigungen",
  "nfc": "NFC-Tags",
  "ar-modus": "AR-Modus",
  "sprachsteuerung": "Sprachsteuerung",
  "offline-konflikte": "Offline-Konflikte",
  "geofencing": "Geofencing",
  "bluetooth-beacons": "Bluetooth Beacons",
  "watch-app": "Apple Watch App",
  "sprachassistent": "Siri & Google Assistant",
  "offline-karten": "Offline-Karten",
  "zeiterfassung": "Zeiterfassung",
  "ki-chat": "KI-Chat",
  "schichtuebergabe": "Schichtübergabe",
  "lieferverfolgung": "Lieferverfolgung",
  "garantieansprueche": "Garantieansprüche",
  "sicherheit": "Sicherheit",
  "budgets": "Budgets",
  "wiederkehrende-bestellungen": "Wiederkehrende Bestellungen"
}
