import type { Session } from "../session-store";
import type {
  DashboardStats,
  ScanResult,
  Commission,
  CommissionEntry,
} from "../api-types";

// ── Session ──────────────────────────────────────────────────────────────────

export const DEMO_SESSION: Session = {
  user: {
    id: "demo-user-123",
    email: "demo@logistikapp.ch",
    name: "Max Muster",
    role: "user",
    image: null,
  },
  token: "demo-token-xxx",
};

// ── Org ───────────────────────────────────────────────────────────────────────

export const DEMO_ORG_ID = "demo-org-456";

// ── Dashboard Stats ───────────────────────────────────────────────────────────

export const DEMO_DASHBOARD_STATS: DashboardStats = {
  materials: 148,
  tools: 37,
  keys: 12,
  users: 5,
  maxUsers: 10,
  lowStockCount: 3,
  expiringCount: 2,
  overdueToolsCount: 1,
};

// ── Commissions ───────────────────────────────────────────────────────────────

export const DEMO_COMMISSIONS: Commission[] = [
  {
    id: "commission-001",
    name: "Baustelle Zürich Altstetten",
    number: 1001,
    manualNumber: "BS-2024-001",
    status: "in_progress",
    notes: "Rohbau EG fertigstellen bis Ende Woche",
    targetLocationId: "loc-001",
    targetLocationName: "Lager Zürich",
    customerId: "cust-001",
    customerName: "Baugenossenschaft Altstetten",
    responsibleId: "demo-user-123",
    responsibleName: "Max Muster",
    entryCount: 4,
    createdAt: "2024-02-01T08:00:00.000Z",
    updatedAt: "2024-03-10T14:30:00.000Z",
  },
  {
    id: "commission-002",
    name: "Renovation Bern Matte",
    number: 1002,
    manualNumber: "BS-2024-002",
    status: "open",
    notes: "Fassadensanierung, Material noch zu bestellen",
    targetLocationId: "loc-002",
    targetLocationName: "Lager Bern",
    customerId: "cust-002",
    customerName: "Liegenschaftsverwaltung Matte AG",
    responsibleId: "demo-user-123",
    responsibleName: "Max Muster",
    entryCount: 2,
    createdAt: "2024-02-15T09:00:00.000Z",
    updatedAt: "2024-03-12T11:00:00.000Z",
  },
  {
    id: "commission-003",
    name: "Lager Winterthur",
    number: 1003,
    manualNumber: "BS-2024-003",
    status: "open",
    notes: null,
    targetLocationId: "loc-003",
    targetLocationName: "Lager Winterthur",
    customerId: "cust-003",
    customerName: "Winterthur Industrie AG",
    responsibleId: null,
    responsibleName: null,
    entryCount: 3,
    createdAt: "2024-03-01T07:30:00.000Z",
    updatedAt: "2024-03-14T16:00:00.000Z",
  },
  {
    id: "commission-004",
    name: "Umbau Basel Kleinbasel",
    number: 1004,
    manualNumber: "BS-2024-004",
    status: "completed",
    notes: "Abgeschlossen, alle Materialien retourniert",
    targetLocationId: "loc-004",
    targetLocationName: "Lager Basel",
    customerId: "cust-004",
    customerName: "Immobilien Basel GmbH",
    responsibleId: "demo-user-123",
    responsibleName: "Max Muster",
    entryCount: 5,
    createdAt: "2024-01-10T08:00:00.000Z",
    updatedAt: "2024-02-28T17:00:00.000Z",
  },
  {
    id: "commission-005",
    name: "Montage Luzern Tribschen",
    number: 1005,
    manualNumber: "BS-2024-005",
    status: "in_progress",
    notes: "Elektroinstallation 2. OG läuft",
    targetLocationId: "loc-005",
    targetLocationName: "Lager Luzern",
    customerId: "cust-005",
    customerName: "Wohnbau Tribschen AG",
    responsibleId: "demo-user-123",
    responsibleName: "Max Muster",
    entryCount: 3,
    createdAt: "2024-03-05T09:00:00.000Z",
    updatedAt: "2024-03-17T10:15:00.000Z",
  },
];

// ── Commission Entries ────────────────────────────────────────────────────────

export const DEMO_COMMISSION_ENTRIES: Record<string, CommissionEntry[]> = {
  "commission-001": [
    {
      id: "entry-001-1",
      commissionId: "commission-001",
      materialId: "mat-001",
      materialName: "Zement CEM II 42.5",
      materialNumber: "ZEM-001",
      materialUnit: "Sack",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 50,
      pickedQuantity: 50,
      status: "picked",
      notes: null,
      createdAt: "2024-02-01T08:30:00.000Z",
    },
    {
      id: "entry-001-2",
      commissionId: "commission-001",
      materialId: "mat-002",
      materialName: "Armierungseisen 10mm",
      materialNumber: "ARM-010",
      materialUnit: "Stk",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 200,
      pickedQuantity: 180,
      status: "partial",
      notes: "20 Stk nachliefern",
      createdAt: "2024-02-01T08:30:00.000Z",
    },
    {
      id: "entry-001-3",
      commissionId: "commission-001",
      materialId: null,
      materialName: null,
      materialNumber: null,
      materialUnit: null,
      toolId: "tool-001",
      toolName: "Bohrhammer Hilti TE 70",
      toolNumber: "WZ-0042",
      quantity: 1,
      pickedQuantity: 1,
      status: "picked",
      notes: null,
      createdAt: "2024-02-02T07:00:00.000Z",
    },
    {
      id: "entry-001-4",
      commissionId: "commission-001",
      materialId: "mat-003",
      materialName: "Schalungsplatte 21mm",
      materialNumber: "SCH-021",
      materialUnit: "m²",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 80,
      pickedQuantity: 0,
      status: "pending",
      notes: null,
      createdAt: "2024-02-05T09:00:00.000Z",
    },
  ],
  "commission-002": [
    {
      id: "entry-002-1",
      commissionId: "commission-002",
      materialId: "mat-004",
      materialName: "Fassadenfarbe weiss 10L",
      materialNumber: "FAR-WS10",
      materialUnit: "Eimer",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 20,
      pickedQuantity: 0,
      status: "pending",
      notes: "Bestellt, Lieferung KW 13",
      createdAt: "2024-02-15T09:30:00.000Z",
    },
    {
      id: "entry-002-2",
      commissionId: "commission-002",
      materialId: "mat-005",
      materialName: "Dämmplatten EPS 100mm",
      materialNumber: "DAE-EPS100",
      materialUnit: "m²",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 120,
      pickedQuantity: 0,
      status: "pending",
      notes: null,
      createdAt: "2024-02-15T09:30:00.000Z",
    },
  ],
  "commission-003": [
    {
      id: "entry-003-1",
      commissionId: "commission-003",
      materialId: "mat-006",
      materialName: "Palettenregal Rahmen 4m",
      materialNumber: "REG-R4",
      materialUnit: "Stk",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 10,
      pickedQuantity: 10,
      status: "picked",
      notes: null,
      createdAt: "2024-03-01T08:00:00.000Z",
    },
    {
      id: "entry-003-2",
      commissionId: "commission-003",
      materialId: "mat-007",
      materialName: "Regalträger 1200mm",
      materialNumber: "REG-T12",
      materialUnit: "Paar",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 40,
      pickedQuantity: 40,
      status: "picked",
      notes: null,
      createdAt: "2024-03-01T08:00:00.000Z",
    },
    {
      id: "entry-003-3",
      commissionId: "commission-003",
      materialId: null,
      materialName: null,
      materialNumber: null,
      materialUnit: null,
      toolId: "tool-002",
      toolName: "Gabelstapler Still FM-X",
      toolNumber: "WZ-0018",
      quantity: 1,
      pickedQuantity: 0,
      status: "pending",
      notes: "Noch nicht abgeholt",
      createdAt: "2024-03-02T07:30:00.000Z",
    },
  ],
  "commission-004": [
    {
      id: "entry-004-1",
      commissionId: "commission-004",
      materialId: "mat-008",
      materialName: "Rigipsplatten 12.5mm",
      materialNumber: "RIG-125",
      materialUnit: "Stk",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 100,
      pickedQuantity: 100,
      status: "picked",
      notes: null,
      createdAt: "2024-01-10T08:30:00.000Z",
    },
    {
      id: "entry-004-2",
      commissionId: "commission-004",
      materialId: "mat-009",
      materialName: "Spachtel Knauf Uniflott 5kg",
      materialNumber: "SPA-KU5",
      materialUnit: "Eimer",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 15,
      pickedQuantity: 15,
      status: "picked",
      notes: null,
      createdAt: "2024-01-10T08:30:00.000Z",
    },
  ],
  "commission-005": [
    {
      id: "entry-005-1",
      commissionId: "commission-005",
      materialId: "mat-010",
      materialName: "NYM-J Kabel 3x1.5mm²",
      materialNumber: "KAB-NYM315",
      materialUnit: "m",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 500,
      pickedQuantity: 300,
      status: "partial",
      notes: null,
      createdAt: "2024-03-05T09:30:00.000Z",
    },
    {
      id: "entry-005-2",
      commissionId: "commission-005",
      materialId: "mat-011",
      materialName: "Unterputzdose 68mm",
      materialNumber: "DOS-UP68",
      materialUnit: "Stk",
      toolId: null,
      toolName: null,
      toolNumber: null,
      quantity: 80,
      pickedQuantity: 80,
      status: "picked",
      notes: null,
      createdAt: "2024-03-05T09:30:00.000Z",
    },
    {
      id: "entry-005-3",
      commissionId: "commission-005",
      materialId: null,
      materialName: null,
      materialNumber: null,
      materialUnit: null,
      toolId: "tool-003",
      toolName: "Kabelmessgerät Fluke 1664 FC",
      toolNumber: "WZ-0099",
      quantity: 1,
      pickedQuantity: 1,
      status: "picked",
      notes: null,
      createdAt: "2024-03-06T07:00:00.000Z",
    },
  ],
};

// ── Scan Result ───────────────────────────────────────────────────────────────

export const DEMO_SCAN_RESULT: ScanResult = {
  type: "material",
  item: {
    id: "mat-001",
    name: "Zement CEM II 42.5",
    number: "ZEM-001",
    unit: "Sack",
    quantity: 25,
    minQuantity: 20,
    locationId: "loc-001",
    locationName: "Lager Zürich",
    barcode: "7612345678901",
    notes: "Standardzement für Hochbau",
    createdAt: "2023-06-01T10:00:00.000Z",
    updatedAt: "2024-03-15T08:00:00.000Z",
  },
};
